// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.StyleInAllThings.API.Data;

#nullable disable

namespace Shop.StyleInAllThings.API.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20231020142609_fix category mistake")]
    partial class fixcategorymistake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.StyleInAllThings.API.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Shop.StyleInAllThings.API.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Shop.StyleInAllThings.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A stylish yellow sofa that will look great under the interior",
                            ImageURL = "/images/Sofa/sofa1.png",
                            Name = "Sofa Nemo Velvet Yellow",
                            Price = 630m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "The stylish Atlanta sofa, straight, with a reliable transformation mechanism 'Eurocook' is designed for daily use.",
                            ImageURL = "/images/Sofa/sofa2.png",
                            Name = "Sofa Atlanta",
                            Price = 459m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Original design, straight lines, representative appearance, wide seat space and moderately wide armrests with firmware",
                            ImageURL = "/images/Sofa/sofa3.png",
                            Name = "CORNER sofa Vermont",
                            Price = 599m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Simple and flawless appearance with plain faux suede upholstery.",
                            ImageURL = "/images/Sofa/sofa4.png",
                            Name = "Good story sofa",
                            Price = 580m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Anatomical sofa bed Domo PRO is the designer of your ideal sleep.",
                            ImageURL = "/images/Sofa/sofa5.png",
                            Name = "Domo Pro corner sofa",
                            Price = 30m,
                            Quantity = 85
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Very comfortable white leather home chair",
                            ImageURL = "/images/Chairs/chair1.png",
                            Name = "White Leather Home Chair",
                            Price = 90m,
                            Quantity = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Very comfortable chair with pillow for home",
                            ImageURL = "/images/Chairs/chair2.png",
                            Name = "Chair with pillow",
                            Price = 50m,
                            Quantity = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Very comfortable stylish high chair",
                            ImageURL = "/images/Chairs/chair3.png",
                            Name = "High chair",
                            Price = 160m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Very a comfortable armchair with a green cushion for your interior",
                            ImageURL = "/images/Chairs/chair4.png",
                            Name = "Chair with a green cushion",
                            Price = 120m,
                            Quantity = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Silver-colored computer chair",
                            ImageURL = "/images/Chairs/chair5.png",
                            Name = "Computer chair",
                            Price = 210m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Perfect chair suitable for both kitchen and living room",
                            ImageURL = "/images/Chairs/chair6.png",
                            Name = "Pink chair",
                            Price = 60m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Standard double bed in your bedroom",
                            ImageURL = "/images/Bed/bed1.png",
                            Name = "Double bed",
                            Price = 450m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "A comfortable bed for a comfortable stay. High quality materials and soft fillers will contribute to complete muscle relaxation and sound sleep.",
                            ImageURL = "/images/Bed/bed2.png",
                            Name = "Empire Suite bed with lifting mechanism",
                            Price = 790m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "A double soft bed with a high headboard. This magnificent bed provides a comfortable sleeping place for you and your significant other.",
                            ImageURL = "/images/Bed/bed3.png",
                            Name = "Nicoletti Lux bed with lifting mechanism",
                            Price = 500m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "There is a sense of modernity and naturalness in the model, unity with your soulmate and complete freedom for individuality.",
                            ImageURL = "/images/Bed/bed4.png",
                            Name = "AGATHA - bed",
                            Price = 600m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "The Piastre bed is made of solid oak with a thickness of 40 mm, which makes the bed strong and solid. Thanks to the laconic design, the bed looks weightless and floats freely in the room.",
                            ImageURL = "/images/Bed/bed5.png",
                            Name = "Bed made of solid oak Piastre",
                            Price = 690m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "The bed from the LINDA collection is a combination of modern design trends, impeccable quality and environmentally friendly materials.",
                            ImageURL = "/images/Bed/bed6.png",
                            Name = "LINDA bed",
                            Price = 710m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Excellent dining table made in loft style",
                            ImageURL = "/images/Table/table1.png",
                            Name = "Dining table Lagus",
                            Price = 300m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "The unusual shape of the base makes the table not only practical, but also decorative. A stylish addition to your interior",
                            ImageURL = "/images/Table/table2.png",
                            Name = "Millwood Cape Town Dining Table",
                            Price = 220m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "The classic rectangular table top is located on a chipboard base and four stable metal legs of contrasting color.",
                            ImageURL = "/images/Table/table3.png",
                            Name = "Kitchen table Reima 5",
                            Price = 250m,
                            Quantity = 190
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Legs are an array of alder, the table top is MDF, lined with natural oak veneer, covered with white enamel,",
                            ImageURL = "/images/Table/table4.png",
                            Name = "Bacchus 110 dining table",
                            Price = 210m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Original table in a modern style will be a great addition to the kitchen or dining area. The round table top is made of MDF, painted white. Legs made of metal painted in the color of wood",
                            ImageURL = "/images/Table/table5.png",
                            Name = "DOLCE NEWECONOM table",
                            Price = 140m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Stylish coffee table will fit perfectly into your interior",
                            ImageURL = "/images/Table/table6.png",
                            Name = "Coffee table Halmar Mariffka",
                            Price = 170m,
                            Quantity = 34
                        });
                });

            modelBuilder.Entity("Shop.StyleInAllThings.API.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sofas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chairs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beds"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tables"
                        });
                });

            modelBuilder.Entity("Shop.StyleInAllThings.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sarah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
